services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
      POSTGRES_SSL_MODE: disable 
    ports:
      - '5432:5432'
    volumes:
      - ktaxapp:/var/lib/postgresql/data

volumes:
  ktaxapp:
    driver: local
